### ISSUE TITLE
Bad Gateway on channels

### ISSUE THREAD

**Issue by kax0** [toomuchio/plex-nginx-reverseproxy#13]
Hi,

I'm having trouble with a few channels that use `..video/` url for example [Sub-Zero](https://github.com/pannal/Sub-Zero.bundle).

I keep getting `502 Bad Gateway` on the when opening the channel:
> `https://domain.xyz/video/subzero?X-Plex-Product=...`

I tried with port 32400:
>  `https://domain.xyz:32400/video/subzero?X-Plex-Product=...`

and it works.. 

Any ideas?

**Comment by toomuchio** [comment]
Sure seems like a bug I'll debug and confirm shortly.

**Comment by toomuchio** [comment]
Indecently can't seem to get this plugin to work correctly on my Plex server. Like... I just can't figure out how to configure it and stuff...

Can you post some access logs just the relevant requests. The plugin may be getting redirected to /web due to the rewrite rule. If it is hopefully there's something in the request we can use to identify it and exclude it from that rewrite.

**Comment by toomuchio** [comment]
Closing will re-open if I ever get recreation steps unable to recreate the issue or verify this issue.
