### ISSUE TITLE
Downloading from Plex, stops after 1024MB

### ISSUE THREAD

**Issue by savahu** [toomuchio/plex-nginx-reverseproxy#4]
Having someone problems with downloading (not streaming) movies from Plex, using this Nginx configuration.
The downloads stop after exactly 1024MB.
Any else tried to download something from their Plex server behind Nginx?

**Comment by toomuchio** [comment]
Hmm well that's not good!

Perhaps it's related to proxy_max_temp_file_size, try adding under the proxy buffering stuff:
proxy_max_temp_file_size 0; I think that disables the limits.
Otherwise something like:
proxy_max_temp_file_size 10240;
Will set the upper limit to a more reasonable 10gb, which should be enough for downloading media.

Reload and let me know if that works I'll update the conf, I can't test it currently. I can take a look later though.

**Comment by savahu** [comment]
Unfortunately that doesn't stop this from happening.. 
And in the config, 'proxy_buffering' was already disabled so 'proxy_max_temp_file_size' should have no effect.

I tried downloading a movie, connected to a remote plex server directly on the external IP without Nginx, and the download still stopped after 1024MB!

I think this might be a bug in Plex itself, it would be nice if people could reproduce this.

This thread on the Plex forum is about the issue: https://forums.plex.tv/discussion/256039/download-stopping-at-exactly-1024mb

**Comment by toomuchio** [comment]
I figured that was probably the case, but you never know. Worth a shot. I'll close this issue since it's obviously a Plex issue.

**Comment by ultimate255** [comment]
I was just experiencing a similar issue, where my streams would buffer endlessly and downloads through plex would stop at around ~1 gigabyte.

~~I was able to fix it by disabling the Brotli compression through Cloudflare. (Speed > Optimization > Brotli)~~

Edit:
The issue still persists. Only chrome/chromecast seems to be affected. 
I have "send_timeout" set.

I tried toggling gzip and http2 within nginx.
When I attempt to download media off of Plex I get "Network Failure" at around ~1 gb. Perhaps it has to do with compression or size mismatch of the file?

I am still looking for a solution.
